# Definizione dei servizi (container)
services:
  # Servizio per il database PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: rdldb
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rdldb
      PG_CRYPTO_KEY: "YourSuperSecretKeyGoesHere"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/init.sql
#    networks:
#      - spring-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rdlbe
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rdldb:5432/rdldb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      PG_CRYPTO_KEY: "YourSuperSecretKeyGoesHere"
#    networks:
#      - spring-net

# Definizione dei volumi
volumes:
  postgres_data:
    driver: local

# Definizione della rete custom
networks:
  spring-net:
    driver: bridge