spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/rdldb
spring.datasource.username=admin
spring.datasource.password=admin
app.security.encryption-key=${PG_CRYPTO_KEY}
logging.level.org.springframework.security=DEBUG