# Configurazione Database PostgreSQL
#DB_URL: jdbc:postgresql://tst-acta-coto01-pdb01.csi.it:5432/PG15DEV01
#DB_USER: actadb_f4
#DB_PASSWORD: mypass
#DB_DRIVER: org.postgresql.Driver

server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: scartobl

  jpa:
    hibernate:
      ddl-auto: none

  caching:
    messages: 900000

logging:
  level:
    root: "warn"
    com.rdlbe: "debug"
    org.springframework.jdbc.core: "TRACE"