-- Creazione di un tipo ENUM personalizzato per i ruoli.
-- Questo va eseguito prima della creazione della tabella 'utenti'.
CREATE TYPE ruolo_enum AS ENUM ('ADMIN', 'USER');

-- Creazione della tabella 'utenti'
CREATE TABLE users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(100) NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        data_nascita DATE,
        ruolo ruolo_enum NOT NULL
);


-- Creazione della tabella 'classi'
CREATE TABLE classrooms (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        titolo VARCHAR(150) NOT NULL,
        descrizione TEXT,
        data_ora_inizio TIMESTAMP,
        data_ora_fine TIMESTAMP
);

ALTER TABLE users RENAME COLUMN stato TO state;
ALTER TABLE users RENAME COLUMN crediti TO credits;


INSERT INTO classrooms (titolo, descrizione, data_ora_inizio, data_ora_fine) VALUES ('Informatica', 'Classe di Informatica', null, null)

INSERT INTO users (nome, email, data_nascita, ruolo) VALUES ('Maria', 'maria.akl@gmail.com', null, 'ADMIN')


ALTER TABLE classrooms RENAME COLUMN date_start_time TO date;
ALTER TABLE classrooms ALTER COLUMN date TYPE DATE;
ALTER TABLE classrooms ADD COLUMN time TIME;
ALTER TABLE classrooms ADD COLUMN duration integer;

ALTER TABLE classrooms ADD COLUMN link TEXT;

