CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Pulisce l'ambiente in caso di riesecuzione dello script
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS inscriptions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS classrooms;
DROP TYPE IF EXISTS ruolo_enum;


-- =================================================================
-- 1. Tipi ENUM e Creazione Tabelle
-- =================================================================

-- Creazione di un tipo ENUM personalizzato per i ruoli.
CREATE TYPE ruolo_enum AS ENUM ('ADMIN', 'USER');

-- Creazione della tabella 'users' (versione finale consolidata)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    password BYTEA NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    birth_date DATE,
    role ruolo_enum NOT NULL,
    state BOOLEAN NOT NULL DEFAULT true,
    credits INTEGER NOT NULL DEFAULT 0
);

-- Creazione della tabella 'classrooms' (versione finale consolidata)
CREATE TABLE classrooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    link VARCHAR(255),

    max_seats INTEGER DEFAULT 10,
    is_active BOOLEAN DEFAULT true,
    date DATE,
    time TIME,
    duration INTEGER -- Durata in minuti
);

-- Creazione della tabella 'inscriptions' per collegare utenti e aule
CREATE TABLE inscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    classroom_id BIGINT NOT NULL,
    inscription_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	registration BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_classroom FOREIGN KEY(classroom_id) REFERENCES classrooms(id) ON DELETE CASCADE,
    -- Impedisce a un utente di iscriversi due volte alla stessa classe
    UNIQUE (user_id, classroom_id)
);

-- Creazione della tabella 'documents' con validazione Base64


-- =================================================================
-- 2. Inserimento dei Dati di Esempio
-- =================================================================

-- Inserimento utenti
-- Nota: le password dovrebbero essere hashate
INSERT INTO users (username, first_name, last_name, password, email, birth_date, role, credits) VALUES
('mariorossi', 'Mario', 'Rossi', PGP_SYM_ENCRYPT('$2a$10$/U/UKctGlrRKrPQMnhuOtuoavO87Aa3sZlSHOw5z2UZOtaGitKfDO', 'YourSuperSecretKeyGoesHere'), 'mario.rossi@email.com', '1990-05-15', 'ADMIN', 100), --- password: password123
('lucabianchi', 'Luca', 'Bianchi', PGP_SYM_ENCRYPT('$2a$10$8rMNrpr79zDndb54/aRF4.ZHz0yL4d8qX9BPnRyijavZfTpmLU3Ju', 'YourSuperSecretKeyGoesHere'), 'luca.bianchi@email.com', '1995-11-20', 'USER', 50), --- password: password456
('annagreen', 'Anna', 'Verdi', PGP_SYM_ENCRYPT('$2a$10$ODhPyS6.PKwjvLL3wkACBuJzBOm936MC58mYjuuhwc8qu12bv57VK', 'YourSuperSecretKeyGoesHere'), 'anna.verdi@email.com', '1998-02-10', 'USER', 75), --- password: password789
('diocane', 'Domenico', 'Muscillo', PGP_SYM_ENCRYPT('$2a$10$ODhPyS6.PKwjvLL3wkACBuJzBOm936MC58mYjuuhwc8qu12bv57VK', 'YourSuperSecretKeyGoesHere'), 'domenicomuscillo13@gmail.com', '2000-06-01', 'ADMIN', 1000000), --- password: password789
('peugeot208', 'Maria', 'Akl', PGP_SYM_ENCRYPT('$2a$10$ODhPyS6.PKwjvLL3wkACBuJzBOm936MC58mYjuuhwc8qu12bv57VK', 'YourSuperSecretKeyGoesHere'), 'maria2000akl@gmail.com', '2000-01-01', 'ADMIN', 1000000); --- password: password789

-- Inserimento aule
INSERT INTO classrooms (name, description, link, max_seats, date, time, duration) VALUES
('Corso Base di SQL', 'Impara le basi dei database relazionali e del linguaggio SQL.', 'https://meet.google.com/sql-base', 15, '2025-10-10', '09:00:00', 120),
('Introduzione a Python', 'Un corso per principianti per iniziare a programmare con Python.', 'https://meet.google.com/python-intro', 20, '2025-10-10', '14:00:00', 90),
('Web Development Avanzato', 'Approfondimenti su framework moderni e best practice.', 'https://meet.google.com/web-advanced', 10, '2025-10-12', '10:00:00', 180);

-- Inserimento iscrizioni (colleghiamo utenti e aule)
-- Mario si iscrive a SQL e Web
INSERT INTO inscriptions (user_id, classroom_id) VALUES
(1, 1),
(1, 3);
-- Luca si iscrive a Python
INSERT INTO inscriptions (user_id, classroom_id) VALUES
(2, 2);
-- Anna si iscrive a tutti i corsi
INSERT INTO inscriptions (user_id, classroom_id) VALUES
(3, 1),
(3, 2),
(3, 3);

-- Inserimento documenti (con stringhe Base64 valide)
-- "Ciao Mondo" -> Q2lhbyBNb25kbw==
-- "Test Documento" -> VGVzdCBEb2N1bWVudG8=
INSERT INTO documents (user_id, content) VALUES
(1, 'Q2lhbyBNb25kbw=='),
(2, 'VGVzdCBEb2N1bWVudG8=');

-- Esempio di INSERT che fallirebbe a causa del CHECK constraint (non puoi eseguirlo)
-- INSERT INTO documents (user_id, content) VALUES (1, 'Questa non è una stringa base64!');

--aggiunta campo user_level alla tabella user
ALTER TABLE users
    ADD COLUMN user_level VARCHAR(20) NOT NULL DEFAULT 'BEGINNER';


DROP TABLE IF EXISTS documents CASCADE;

CREATE TABLE documents (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    file_name VARCHAR(255),
    content_type VARCHAR(100),
    content BYTEA NOT NULL, -- <── binario (Postgres usa BYTEA)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);