-- Creazione di un tipo ENUM personalizzato per i ruoli.
-- Questo va eseguito prima della creazione della tabella 'utenti'.
CREATE TYPE ruolo_enum AS ENUM ('ADMIN', 'USER');

-- Creazione della tabella 'utenti'
CREATE TABLE utenti (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(100) NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        data_nascita DATE,
        ruolo ruolo_enum NOT NULL
);


-- Creazione della tabella 'classi'
CREATE TABLE classi (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        titolo VARCHAR(150) NOT NULL,
        descrizione TEXT,
        data_ora_inizio TIMESTAMP,
        data_ora_fine TIMESTAMP
);


-- Creazione della tabella di join 'utenti_classi' (nessuna modifica necessaria qui)
CREATE TABLE utenti_classi (
        utente_id BIGINT,
        classe_id BIGINT,
        PRIMARY KEY (utente_id, classe_id),
        FOREIGN KEY (utente_id) REFERENCES utenti(id) ON DELETE CASCADE,
        FOREIGN KEY (classe_id) REFERENCES classi(id) ON DELETE CASCADE
);

INSERT INTO classi (titolo, descrizione, data_ora_inizio, data_ora_fine) VALUES ('Informatica', 'Classe di Informatica', null, null)

INSERT INTO utenti (nome, email, data_nascita, ruolo) VALUES ('Maria', 'maria.akl@gmail.com', null, 'ADMIN')